### ISSUE TITLE
Some lights just stop working.

### ISSUE THREAD

**Issue by Death404** [drumfreak/homebridge-tuya-colorlight#1]
I have an issue where one of the lights that previously worked fine no longer works through the plugin. It still works in the Smart Life app and I have even repaired it to see if that fixed it, and it did not.

I would provide debug info but there is none, right before it gets to the device homebridge just freezes, if I change enabled to false everything starts fine. 

I have 3 other lights that work perfectly, ordered at exact same time and this light worked fine a week before just stopping. Any ideas how I can debug further?

The product ID is:

sMk7hhVsN5KBWbwV 

and the link to where I bought them is:

https://www.ebay.com/itm/2Pcs-WiFi-Remote-Control-Smart-LED-Bulb-7W-E26-RGB-Light-2-4GHz-For-Alexa-Google/192496430203?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

**Comment by Death404** [comment]
I lied, this is the debug info with debug enabled on device and homebridge. I cant get anything more verbose. I am using `DEBUG=* homebridge-d` to start the service.

```
[2018-4-25 20:55:58] [Tuya Color Light - Room 2] ~~~!~~~  Tuya Color Light Room 2 Ip is defined as 192.168.X.X
[2018-4-25 20:55:58] [Tuya Color Light - Room 2] ~~~!~~~  Tuya API Settings - Retries: 1 Debug: true Min Timeout: 100 Max Timeout: 1000
[2018-4-25 20:55:58] [Room 2] Polling at interval... 120 seconds
[2018-4-25 20:55:58] [Tuya Color Light - Room 2] ~~~!~~~  Payload: 
[2018-4-25 20:55:58] [Tuya Color Light - Room 2] ~~~!~~~  { gwId: '05200399bcddc2e1163e', devId: '05200399bcddc2e1163e' }
[2018-4-25 20:55:58] [Tuya Color Light - Room 2] ~~~!~~~  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Sending GET request: Room 2
```

**Comment by drumfreak** [comment]
When it stops working, do you have the Tuya app running on your phone?  Does it start working again? Maybe try tweaking up the timeout settings and retries.

**Comment by drumfreak** [comment]
Also, add:
`superDebug: true`
To you the accessory in your config file to really get some detailed output.

**Comment by Death404** [comment]
Thanks a lot for that!

So, the light just magically was working again this morning. o.O

I turned on superdebug on that light and will check back in if/when it happens again. thanks a lot!

Also, The app definitely was not running on my phone. I even made sure to close the app out and restart homebridge and the same thing was still happening.

**Comment by drumfreak** [comment]
Strange!  The timeout settings should help with that. Tweak them up, and double check that nothing else is controlling the light such as Alexa, IFTT and etc.  enjoy!
